Fit 92 2 wheel of life pin
CamiloHernandezC/GRLPWR pull request #156
Opened 2024-05-24 21:55 UTC by leramirezga

2024-06-17 13:55 UTC, CamiloHernandezC requested changes

2024-06-17 13:55 UTC, CamiloHernandezC commented on app/User.php
> -    use Notifiable, Achiever;
Revisar que esto esté bien. Puede verificar en la documentación

2024-06-17 13:55 UTC, CamiloHernandezC commented on app/Achievements/FamilyAndFriendsAchievement.php
> +    public $description = "Felicidades, tienes tu pin por ser feliz!";
Dele un Slug y una descripción coherente a cada pin

2024-06-17 14:22 UTC, leramirezga commented on app/User.php
> -    use Notifiable, Achiever;
Esto permite al modelo (User) poder interactuar con los logros, permite desbloquear y realizar progresos a la entidad 

https://assada.github.io/laravel-achievements/#:~:text=Achievements%20%23back%20to%20top%201%20Registering%20an%20Achiever,in%20the%20app%5CAchievements%20directory.%203%20Unlocking%20an%20Achievement

![image](https://github.com/CamiloHernandezC/GRLPWR/assets/74741831/c71e6524-7f69-4572-9036-731a1e677491)

2024-06-24 01:44 UTC, CamiloHernandezC approved these changes

2024-06-24 01:45 UTC, merged